<a href="https://colab.research.google.com/github/krishhh-na/Tareas-FIS1344-1/blob/main/Tarea_5_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
A = np.array([[2,0,0,0,0],
              [1,1.4,0,0,0],
              [1.4,2,1.1,0,0],
              [2.3,3.3,3,0.4,0],
              [0.3,1,5,2,3]], dtype=float)
L = np.identity(5, dtype=float)
U = np.zeros((5,5), dtype=float)

U[0, :] = A[0, :]            #primera iteracion
display(U)
L[:, 0] = A[:, 0] / U[0,0]
display(L)
A_prime = A - L@U
display(A_prime)

U[1, 1:] = A_prime[1,1:]          #segunda iteracion
L[1:,1] = A_prime[1:,1] / U[1,1]
A_prime2 = np.zeros((5,5))
A_prime2 = A - L@U
display(A_prime2)

U[2,2:] = A_prime2[2,2:]            #tercera iteracion
L[2:,2] = A_prime2[2:,2] / U[2,2]
A_prime3 = A - L@U
display(A_prime3)

U[3,3:] = A_prime3[3,3:]            #cuarta iteracion
L[3:,3] = A_prime3[3:,3] / U[3,3]
A_prime4 = A - L@U
display(A_prime4)

U[4,4:] = A_prime4[4,4]

print("matriz L:")
display(L)

print("matriz U:")
display(U)


array([[2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 1.  , 0.  , 0.  , 0.  ],
       [0.7 , 0.  , 1.  , 0.  , 0.  ],
       [1.15, 0.  , 0.  , 1.  , 0.  ],
       [0.15, 0.  , 0.  , 0.  , 1.  ]])

array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 1.4, 0. , 0. , 0. ],
       [0. , 2. , 1.1, 0. , 0. ],
       [0. , 3.3, 3. , 0.4, 0. ],
       [0. , 1. , 5. , 2. , 3. ]])

array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1.1, 0. , 0. ],
       [0. , 0. , 3. , 0.4, 0. ],
       [0. , 0. , 5. , 2. , 3. ]])

array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 2. , 3. ]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3.]])

matriz L:


array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        , 0.        , 0.        ],
       [0.7       , 1.42857143, 1.        , 0.        , 0.        ],
       [1.15      , 2.35714286, 2.72727273, 1.        , 0.        ],
       [0.15      , 0.71428571, 4.54545455, 5.        , 1.        ]])

matriz U:


array([[2. , 0. , 0. , 0. , 0. ],
       [0. , 1.4, 0. , 0. , 0. ],
       [0. , 0. , 1.1, 0. , 0. ],
       [0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 3. ]])

La matriz L es distinto de la matriz A porque el algoritmo que usamos para resolver este ejercicio (LU) hace que los elementos de la diagonal princial de L sean igual a 1.

La matriz U no es la matriz identidad ya que este algoritmo hace que los valores de la diagonal principal de A queden en U, sabemos que los valores de la diagonal principal de la matriz identidad son 1, diferentes a los valores de U.